### ISSUE TITLE
Allow virtual attributes to be versioned

### ISSUE THREAD

**Issue by zporter** [vigetlabs/active_versioning#5]
The README mentions overwriting `versioned_attribute_names` in the model. I took this to mean that I could add virtual attributes to be versioned. However, [this blob](https://github.com/vigetlabs/active_versioning/blob/0ec361b53799ebe5c03e649dca10202c5905a857/lib/active_versioning/version_manager.rb#L27-L29) throws the exception because of the reference to `record.attributes`.  Should this read `record.versioned_attribute_names` instead of `record.attributes.keys`?

**Comment by h0tl33t** [comment]
I just ran into this.  This is definitely a bug.  It shouldn't be checking `record.attributes.keys`, but rather `record.versioned_attributes.keys`.
